import uuid
from typing import List
from datetime import datetime, timezone

from core.exceptions import NotFoundException, BadRequestException
from models.document_chunk import DocumentChunk
from repositories.document import DocumentRepository
from repositories.document_chunk import DocumentChunkRepository
from repositories.task import TaskRepository
from services.embedding import EmbeddingService


class RetrievalService:
    """Service responsible for chunking and retrieving document text."""

    def __init__(
        self,
        document_repository: DocumentRepository,
        document_chunk_repository: DocumentChunkRepository,
        task_repository: TaskRepository,
        embedding_service: EmbeddingService,
    ):
        self.document_repository = document_repository
        self.document_chunk_repository = document_chunk_repository
        self.task_repository = task_repository
        self.embedding_service = embedding_service

    async def chunk_document(self, document_id: uuid.UUID, chunk_size: int = 500) -> List[DocumentChunk]:
        """Splits a document's extracted_text into chunks and saves them with embeddings.
        
        Args:
            document_id: UUID of the document to chunk.
            chunk_size: Number of characters per chunk.
            
        Returns:
            List of created DocumentChunk entities.
        """
        document = await self.document_repository.get(document_id)
        if not document:
            raise NotFoundException(detail="Document not found.")

        if not document.extracted_text:
            raise BadRequestException(detail="Document has no extracted text to chunk.")

        text = document.extracted_text
        
        # We need to chunk first, but we are supposed to skip generating embeddings for chunks that already have them.
        # However, chunk_document is meant to re-chunk the whole document.
        # Wait, the requirement says: "Skip regenerating embeddings for chunks that already have embeddings generated by the current model unless a forced reindex is requested."
        # If we re-chunk, the old chunks are deleted. Let's fetch existing chunks first.
        existing_chunks = await self.document_chunk_repository.get_by_document(document_id)
        existing_texts = {c.text: c for c in existing_chunks if c.embedding_model == self.embedding_service.model_name and c.embedding is not None}
        
        # Delete existing chunks for this document to replace them
        await self.document_chunk_repository.delete_by_document(document_id)

        # Simple character-based chunking
        chunk_texts = []
        for i in range(0, len(text), chunk_size):
            chunk_texts.append(text[i : i + chunk_size])

        # Batch generate embeddings only for new texts
        texts_to_embed = [t for t in chunk_texts if t not in existing_texts]
        
        embeddings_dict = {}
        if texts_to_embed:
            new_embeddings = self.embedding_service.generate_embeddings(texts_to_embed)
            for t, emb in zip(texts_to_embed, new_embeddings):
                embeddings_dict[t] = emb
                
        now = datetime.now(timezone.utc)
        chunks = []
        
        for idx, chunk_text in enumerate(chunk_texts):
            if chunk_text in existing_texts:
                emb = existing_texts[chunk_text].embedding
            else:
                emb = embeddings_dict[chunk_text]
                
            chunk = await self.document_chunk_repository.create(
                document_id=document_id,
                chunk_index=idx,
                text=chunk_text,
                token_count=len(chunk_text.split()),  # Mock token count
                embedding=emb,
                embedding_model=self.embedding_service.model_name,
                embedded_at=now,
                embedding_dimension=len(emb) if emb else None
            )
            chunks.append(chunk)

        return chunks

    async def reindex_all_chunks(self) -> int:
        """Finds all chunks without embeddings from the current model and generates them.
        
        Returns:
            The number of chunks updated.
        """
        chunks_to_update = await self.document_chunk_repository.get_chunks_without_embeddings(
            self.embedding_service.model_name
        )
        
        if not chunks_to_update:
            return 0
            
        texts_to_embed = [c.text for c in chunks_to_update]
        embeddings = self.embedding_service.generate_embeddings(texts_to_embed)
        
        now = datetime.now(timezone.utc)
        for chunk, emb in zip(chunks_to_update, embeddings):
            await self.document_chunk_repository.update(
                chunk,
                embedding=emb,
                embedding_model=self.embedding_service.model_name,
                embedded_at=now,
                embedding_dimension=len(emb) if emb else None
            )
            
        return len(chunks_to_update)

    async def retrieve_chunks(self, task_id: uuid.UUID, top_k: int = 3) -> List[dict]:
        """Retrieves and scores chunks for a given task using semantic search.
        
        Args:
            task_id: UUID of the task.
            top_k: Number of chunks to return.
            
        Returns:
            List of dictionaries containing 'chunk' and 'score', sorted by score descending.
        """
        task = await self.task_repository.get(task_id)
        if not task:
            raise NotFoundException(detail="Task not found.")

        if not task.document_id:
            raise BadRequestException(detail="Task does not have an associated document.")

        chunks = await self.document_chunk_repository.get_by_document(task.document_id)
        
        if not chunks:
            return []
            
        # Filter chunks that actually have embeddings
        valid_chunks = [c for c in chunks if c.embedding is not None]
        if not valid_chunks:
            return []

        search_text = f"{task.title or ''} {task.description or ''}"
        query_embedding = self.embedding_service.generate_embedding(search_text)
        
        chunk_embeddings = [c.embedding for c in valid_chunks]
        
        similarities = self.embedding_service.compute_similarities(query_embedding, chunk_embeddings)
        
        scored_chunks = []
        for chunk, score in zip(valid_chunks, similarities):
            scored_chunks.append({
                "chunk": chunk,
                "score": float(score)  # Convert from numpy float
            })

        # Sort by score descending
        scored_chunks.sort(key=lambda x: x["score"], reverse=True)

        return scored_chunks[:top_k]
