"""Add prompt templates

Revision ID: de47af914a0d
Revises: 8b0b5259ac35
Create Date: 2026-07-27 16:54:30.482897

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import uuid


# revision identifiers, used by Alembic.
revision: str = "de47af914a0d"
down_revision: Union[str, Sequence[str], None] = "8b0b5259ac35"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prompt_templates",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("system_prompt", sa.Text(), nullable=True),
        sa.Column("user_prompt_template", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("evaluation_runs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("prompt_template_id", sa.Uuid(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_evaluation_runs_prompt_template_id"),
            ["prompt_template_id"],
            unique=False,
        )
        batch_op.create_foreign_key(
            "fk_evaluation_runs_prompt_template_id",
            "prompt_templates",
            ["prompt_template_id"],
            ["id"],
            ondelete="SET NULL",
        )

    with op.batch_alter_table("experiments", schema=None) as batch_op:
        batch_op.add_column(sa.Column("prompt_template_id", sa.Uuid(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_experiments_prompt_template_id"),
            ["prompt_template_id"],
            unique=False,
        )
        batch_op.create_foreign_key(
            "fk_experiments_prompt_template_id",
            "prompt_templates",
            ["prompt_template_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # Insert default prompt template
    op.execute(
        sa.text(
            """
            INSERT INTO prompt_templates (id, name, description, system_prompt, user_prompt_template, version, is_default, created_at, updated_at)
            VALUES (:id, :name, :desc, :sys_prompt, :user_prompt, :version, :is_default, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
            """
        ).bindparams(
            id=uuid.uuid4().hex,
            name="Default RAG Prompt",
            desc="The standard prompt for RAG tasks.",
            sys_prompt="You are an enterprise AI assistant.",
            user_prompt="Task:\\nTitle: {{task_title}}\\nDescription: {{task_description}}\\n\\nRelevant Context:\\n{{retrieved_context}}\\n\\nInstructions:\\nOnly answer using the provided context whenever possible. Do not invent information.\\n\\nAnswer:\\n",
            version=1,
            is_default=True
        )
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("experiments", schema=None) as batch_op:
        batch_op.drop_constraint("fk_experiments_prompt_template_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_experiments_prompt_template_id"))
        batch_op.drop_column("prompt_template_id")

    with op.batch_alter_table("evaluation_runs", schema=None) as batch_op:
        batch_op.drop_constraint("fk_evaluation_runs_prompt_template_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_evaluation_runs_prompt_template_id"))
        batch_op.drop_column("prompt_template_id")

    op.drop_table("prompt_templates")
    # ### end Alembic commands ###
