"""Add extracted_text and content_type to documents

Revision ID: 5b88c38e856c
Revises: 69123479dde7
Create Date: 2026-07-23 11:48:24.025737

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5b88c38e856c"
down_revision: Union[str, Sequence[str], None] = "69123479dde7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents", sa.Column("content_type", sa.String(length=100), nullable=True)
    )
    op.add_column("documents", sa.Column("extracted_text", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "extracted_text")
    op.drop_column("documents", "content_type")
    # ### end Alembic commands ###
